# flake8: noqa

"""
    Genie API

    Augemented Reality Made Easy.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: hello@genie-ar.ch
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from genie.api_client import ApiClient

# import Configuration
from genie.configuration import Configuration

# import exceptions
from genie.exceptions import OpenApiException
from genie.exceptions import ApiAttributeError
from genie.exceptions import ApiTypeError
from genie.exceptions import ApiValueError
from genie.exceptions import ApiKeyError
from genie.exceptions import ApiException
