"""
    Genie API

    Augemented Reality Made Easy.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: hello@genie-ar.ch
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import genie.client
from genie.client.model.customer import Customer


class TestCustomer(unittest.TestCase):
    """Customer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomer(self):
        """Test Customer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Customer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
