"""
    Genie API

    Augemented Reality Made Easy.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: hello@genie-ar.ch
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import genie.client
from genie.client.model.filter_events_enum import FilterEventsEnum
from genie.client.model.global_statistics_group_by_enum import GlobalStatisticsGroupByEnum
from genie.client.model.report_format_enum import ReportFormatEnum
from genie.client.model.time_range_enum import TimeRangeEnum
globals()['FilterEventsEnum'] = FilterEventsEnum
globals()['GlobalStatisticsGroupByEnum'] = GlobalStatisticsGroupByEnum
globals()['ReportFormatEnum'] = ReportFormatEnum
globals()['TimeRangeEnum'] = TimeRangeEnum
from genie.client.model.global_statistics import GlobalStatistics


class TestGlobalStatistics(unittest.TestCase):
    """GlobalStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalStatistics(self):
        """Test GlobalStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GlobalStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
