"""
    Genie API

    Augemented Reality Made Easy.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: hello@genie-ar.ch
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import genie.client
from genie.client.model.password_reset_confirm import PasswordResetConfirm


class TestPasswordResetConfirm(unittest.TestCase):
    """PasswordResetConfirm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPasswordResetConfirm(self):
        """Test PasswordResetConfirm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PasswordResetConfirm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
