name: 'yago-api-client'
version: '1.0.0'
description: 'Genie REST API Client'
homepage: 'https://bitforge.ch/'
repository: 'https://github.com/bitforge/genie-api-clients'
documentation: 'https://genie-ar.ch/api/doc/'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.1.8'
dev_dependencies:
  test: '>=1.16.0 <1.18.0'
