name: "yago_cloud"
version: "1.3.0"
description: "Yago Cloud API Client for Flutter & Dart"
homepage: https://yago.cloud/
repository: https://github.com/bitforge/yago_api_clients
documentation: https://yago.cloud/api/doc
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  collection: "^1.17.2"
  http: ^1.1.2
  intl: ^0.18.1
  meta: "^1.1.8"
dev_dependencies:
  test: ^1.24.9
