/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api;
using Genie.Model;
using Genie.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Test.Model
{
    /// <summary>
    ///  Class for testing ModelUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelUpdate
        //private ModelUpdate instance;

        public ModelUpdateTests()
        {
            // TODO uncomment below to create an instance of ModelUpdate
            //instance = new ModelUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelUpdate
        /// </summary>
        [Fact]
        public void ModelUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelUpdate
            //Assert.IsType<ModelUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'NameDe'
        /// </summary>
        [Fact]
        public void NameDeTest()
        {
            // TODO unit test for the property 'NameDe'
        }
        /// <summary>
        /// Test the property 'NameEn'
        /// </summary>
        [Fact]
        public void NameEnTest()
        {
            // TODO unit test for the property 'NameEn'
        }
        /// <summary>
        /// Test the property 'NameFr'
        /// </summary>
        [Fact]
        public void NameFrTest()
        {
            // TODO unit test for the property 'NameFr'
        }
        /// <summary>
        /// Test the property 'NameIt'
        /// </summary>
        [Fact]
        public void NameItTest()
        {
            // TODO unit test for the property 'NameIt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DescriptionDe'
        /// </summary>
        [Fact]
        public void DescriptionDeTest()
        {
            // TODO unit test for the property 'DescriptionDe'
        }
        /// <summary>
        /// Test the property 'DescriptionEn'
        /// </summary>
        [Fact]
        public void DescriptionEnTest()
        {
            // TODO unit test for the property 'DescriptionEn'
        }
        /// <summary>
        /// Test the property 'DescriptionFr'
        /// </summary>
        [Fact]
        public void DescriptionFrTest()
        {
            // TODO unit test for the property 'DescriptionFr'
        }
        /// <summary>
        /// Test the property 'DescriptionIt'
        /// </summary>
        [Fact]
        public void DescriptionItTest()
        {
            // TODO unit test for the property 'DescriptionIt'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'SiteUrlDe'
        /// </summary>
        [Fact]
        public void SiteUrlDeTest()
        {
            // TODO unit test for the property 'SiteUrlDe'
        }
        /// <summary>
        /// Test the property 'SiteUrlEn'
        /// </summary>
        [Fact]
        public void SiteUrlEnTest()
        {
            // TODO unit test for the property 'SiteUrlEn'
        }
        /// <summary>
        /// Test the property 'SiteUrlFr'
        /// </summary>
        [Fact]
        public void SiteUrlFrTest()
        {
            // TODO unit test for the property 'SiteUrlFr'
        }
        /// <summary>
        /// Test the property 'SiteUrlIt'
        /// </summary>
        [Fact]
        public void SiteUrlItTest()
        {
            // TODO unit test for the property 'SiteUrlIt'
        }
        /// <summary>
        /// Test the property 'Scaleable'
        /// </summary>
        [Fact]
        public void ScaleableTest()
        {
            // TODO unit test for the property 'Scaleable'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'PriceCurrency'
        /// </summary>
        [Fact]
        public void PriceCurrencyTest()
        {
            // TODO unit test for the property 'PriceCurrency'
        }

    }

}
