/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api;
using Genie.Model;
using Genie.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectCreate
        //private ProjectCreate instance;

        public ProjectCreateTests()
        {
            // TODO uncomment below to create an instance of ProjectCreate
            //instance = new ProjectCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectCreate
        /// </summary>
        [Fact]
        public void ProjectCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectCreate
            //Assert.IsType<ProjectCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
