/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CollectionMethodEnum
 */
@JsonAdapter(CollectionMethodEnum.Adapter.class)
public enum CollectionMethodEnum {
  
  CHARGE_AUTOMATICALLY("charge_automatically"),
  
  SEND_INVOICE("send_invoice");

  private String value;

  CollectionMethodEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CollectionMethodEnum fromValue(String value) {
    for (CollectionMethodEnum b : CollectionMethodEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CollectionMethodEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final CollectionMethodEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CollectionMethodEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CollectionMethodEnum.fromValue(value);
    }
  }
}

