/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets GlobalStatisticsGroupByEnum
 */
@JsonAdapter(GlobalStatisticsGroupByEnum.Adapter.class)
public enum GlobalStatisticsGroupByEnum {
  
  ALL("all"),
  
  EVENTS("events"),
  
  MODELS("models"),
  
  PLATFORMS("platforms"),
  
  LANGUAGES("languages"),
  
  DEVICES("devices"),
  
  BROWSERS("browsers"),
  
  COUNTRIES("countries"),
  
  PROJECTS("projects");

  private String value;

  GlobalStatisticsGroupByEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GlobalStatisticsGroupByEnum fromValue(String value) {
    for (GlobalStatisticsGroupByEnum b : GlobalStatisticsGroupByEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<GlobalStatisticsGroupByEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final GlobalStatisticsGroupByEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GlobalStatisticsGroupByEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GlobalStatisticsGroupByEnum.fromValue(value);
    }
  }
}

