/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import yago.client.models.ModelStatus;

/**
 * Model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-21T17:02:29.236455048+01:00[Europe/Zurich]")
public class Model {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  private UUID project;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAME_DE = "name_de";
  @SerializedName(SERIALIZED_NAME_NAME_DE)
  private String nameDe;

  public static final String SERIALIZED_NAME_NAME_EN = "name_en";
  @SerializedName(SERIALIZED_NAME_NAME_EN)
  private String nameEn;

  public static final String SERIALIZED_NAME_NAME_FR = "name_fr";
  @SerializedName(SERIALIZED_NAME_NAME_FR)
  private String nameFr;

  public static final String SERIALIZED_NAME_NAME_IT = "name_it";
  @SerializedName(SERIALIZED_NAME_NAME_IT)
  private String nameIt;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  private String slug;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private URI image;

  public static final String SERIALIZED_NAME_IMAGE_THUMB = "image_thumb";
  @SerializedName(SERIALIZED_NAME_IMAGE_THUMB)
  private String imageThumb;

  public static final String SERIALIZED_NAME_IMAGE_PREVIEW = "image_preview";
  @SerializedName(SERIALIZED_NAME_IMAGE_PREVIEW)
  private String imagePreview;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ModelStatus status;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DESCRIPTION_DE = "description_de";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_DE)
  private String descriptionDe;

  public static final String SERIALIZED_NAME_DESCRIPTION_EN = "description_en";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_EN)
  private String descriptionEn;

  public static final String SERIALIZED_NAME_DESCRIPTION_FR = "description_fr";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_FR)
  private String descriptionFr;

  public static final String SERIALIZED_NAME_DESCRIPTION_IT = "description_it";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_IT)
  private String descriptionIt;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  private Integer number;

  public static final String SERIALIZED_NAME_SITE_URL = "site_url";
  @SerializedName(SERIALIZED_NAME_SITE_URL)
  private String siteUrl;

  public static final String SERIALIZED_NAME_SITE_URL_DE = "site_url_de";
  @SerializedName(SERIALIZED_NAME_SITE_URL_DE)
  private URI siteUrlDe;

  public static final String SERIALIZED_NAME_SITE_URL_EN = "site_url_en";
  @SerializedName(SERIALIZED_NAME_SITE_URL_EN)
  private URI siteUrlEn;

  public static final String SERIALIZED_NAME_SITE_URL_FR = "site_url_fr";
  @SerializedName(SERIALIZED_NAME_SITE_URL_FR)
  private URI siteUrlFr;

  public static final String SERIALIZED_NAME_SITE_URL_IT = "site_url_it";
  @SerializedName(SERIALIZED_NAME_SITE_URL_IT)
  private URI siteUrlIt;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_PRICE_CURRENCY = "price_currency";
  @SerializedName(SERIALIZED_NAME_PRICE_CURRENCY)
  private String priceCurrency;

  public static final String SERIALIZED_NAME_SCALEABLE = "scaleable";
  @SerializedName(SERIALIZED_NAME_SCALEABLE)
  private Boolean scaleable;

  public static final String SERIALIZED_NAME_GLB = "glb";
  @SerializedName(SERIALIZED_NAME_GLB)
  private URI glb;

  public static final String SERIALIZED_NAME_USDZ = "usdz";
  @SerializedName(SERIALIZED_NAME_USDZ)
  private URI usdz;

  public static final String SERIALIZED_NAME_UNITY_IOS = "unity_ios";
  @SerializedName(SERIALIZED_NAME_UNITY_IOS)
  private URI unityIos;

  public static final String SERIALIZED_NAME_UNITY_ANDROID = "unity_android";
  @SerializedName(SERIALIZED_NAME_UNITY_ANDROID)
  private URI unityAndroid;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  private OffsetDateTime modified;

  public Model() { 
  }

  
  public Model(
     UUID id, 
     String name, 
     String imageThumb, 
     String imagePreview, 
     String description, 
     String siteUrl, 
     String priceCurrency, 
     OffsetDateTime created, 
     OffsetDateTime modified
  ) {
    this();
    this.id = id;
    this.name = name;
    this.imageThumb = imageThumb;
    this.imagePreview = imagePreview;
    this.description = description;
    this.siteUrl = siteUrl;
    this.priceCurrency = priceCurrency;
    this.created = created;
    this.modified = modified;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public UUID getId() {
    return id;
  }




  public Model project(UUID project) {
    
    this.project = project;
    return this;
  }

   /**
   * The project this model belongs to. Cannot be changed once created.
   * @return project
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The project this model belongs to. Cannot be changed once created.")

  public UUID getProject() {
    return project;
  }


  public void setProject(UUID project) {
    this.project = project;
  }


   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }




  public Model nameDe(String nameDe) {
    
    this.nameDe = nameDe;
    return this;
  }

   /**
   * Name will be visible in Android as title.
   * @return nameDe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name will be visible in Android as title.")

  public String getNameDe() {
    return nameDe;
  }


  public void setNameDe(String nameDe) {
    this.nameDe = nameDe;
  }


  public Model nameEn(String nameEn) {
    
    this.nameEn = nameEn;
    return this;
  }

   /**
   * Name will be visible in Android as title.
   * @return nameEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name will be visible in Android as title.")

  public String getNameEn() {
    return nameEn;
  }


  public void setNameEn(String nameEn) {
    this.nameEn = nameEn;
  }


  public Model nameFr(String nameFr) {
    
    this.nameFr = nameFr;
    return this;
  }

   /**
   * Name will be visible in Android as title.
   * @return nameFr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name will be visible in Android as title.")

  public String getNameFr() {
    return nameFr;
  }


  public void setNameFr(String nameFr) {
    this.nameFr = nameFr;
  }


  public Model nameIt(String nameIt) {
    
    this.nameIt = nameIt;
    return this;
  }

   /**
   * Name will be visible in Android as title.
   * @return nameIt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name will be visible in Android as title.")

  public String getNameIt() {
    return nameIt;
  }


  public void setNameIt(String nameIt) {
    this.nameIt = nameIt;
  }


  public Model slug(String slug) {
    
    this.slug = slug;
    return this;
  }

   /**
   * Unique Short-URL for embedding. Cannot be changed once created.
   * @return slug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique Short-URL for embedding. Cannot be changed once created.")

  public String getSlug() {
    return slug;
  }


  public void setSlug(String slug) {
    this.slug = slug;
  }


  public Model image(URI image) {
    
    this.image = image;
    return this;
  }

   /**
   * Preview image of the model (iOS, gallery, sharing, SEO).
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Preview image of the model (iOS, gallery, sharing, SEO).")

  public URI getImage() {
    return image;
  }


  public void setImage(URI image) {
    this.image = image;
  }


   /**
   * Get imageThumb
   * @return imageThumb
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getImageThumb() {
    return imageThumb;
  }




   /**
   * Get imagePreview
   * @return imagePreview
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getImagePreview() {
    return imagePreview;
  }




  public Model status(ModelStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * DRAFT&#x3D;In development, READY&#x3D;Modelling complete, ONLINE&#x3D;Active use.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DRAFT=In development, READY=Modelling complete, ONLINE=Active use.")

  public ModelStatus getStatus() {
    return status;
  }


  public void setStatus(ModelStatus status) {
    this.status = status;
  }


   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getDescription() {
    return description;
  }




  public Model descriptionDe(String descriptionDe) {
    
    this.descriptionDe = descriptionDe;
    return this;
  }

   /**
   * Used when shared as link and for SEO.
   * @return descriptionDe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Used when shared as link and for SEO.")

  public String getDescriptionDe() {
    return descriptionDe;
  }


  public void setDescriptionDe(String descriptionDe) {
    this.descriptionDe = descriptionDe;
  }


  public Model descriptionEn(String descriptionEn) {
    
    this.descriptionEn = descriptionEn;
    return this;
  }

   /**
   * Used when shared as link and for SEO.
   * @return descriptionEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Used when shared as link and for SEO.")

  public String getDescriptionEn() {
    return descriptionEn;
  }


  public void setDescriptionEn(String descriptionEn) {
    this.descriptionEn = descriptionEn;
  }


  public Model descriptionFr(String descriptionFr) {
    
    this.descriptionFr = descriptionFr;
    return this;
  }

   /**
   * Used when shared as link and for SEO.
   * @return descriptionFr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Used when shared as link and for SEO.")

  public String getDescriptionFr() {
    return descriptionFr;
  }


  public void setDescriptionFr(String descriptionFr) {
    this.descriptionFr = descriptionFr;
  }


  public Model descriptionIt(String descriptionIt) {
    
    this.descriptionIt = descriptionIt;
    return this;
  }

   /**
   * Used when shared as link and for SEO.
   * @return descriptionIt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Used when shared as link and for SEO.")

  public String getDescriptionIt() {
    return descriptionIt;
  }


  public void setDescriptionIt(String descriptionIt) {
    this.descriptionIt = descriptionIt;
  }


  public Model number(Integer number) {
    
    this.number = number;
    return this;
  }

   /**
   * Use for custom sort order.
   * minimum: 0
   * maximum: 2147483647
   * @return number
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Use for custom sort order.")

  public Integer getNumber() {
    return number;
  }


  public void setNumber(Integer number) {
    this.number = number;
  }


   /**
   * Get siteUrl
   * @return siteUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSiteUrl() {
    return siteUrl;
  }




  public Model siteUrlDe(URI siteUrlDe) {
    
    this.siteUrlDe = siteUrlDe;
    return this;
  }

   /**
   * Link to the product on your site. Required when using standalone QR codes (e.g. Print).
   * @return siteUrlDe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link to the product on your site. Required when using standalone QR codes (e.g. Print).")

  public URI getSiteUrlDe() {
    return siteUrlDe;
  }


  public void setSiteUrlDe(URI siteUrlDe) {
    this.siteUrlDe = siteUrlDe;
  }


  public Model siteUrlEn(URI siteUrlEn) {
    
    this.siteUrlEn = siteUrlEn;
    return this;
  }

   /**
   * Link to the product on your site. Required when using standalone QR codes (e.g. Print).
   * @return siteUrlEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link to the product on your site. Required when using standalone QR codes (e.g. Print).")

  public URI getSiteUrlEn() {
    return siteUrlEn;
  }


  public void setSiteUrlEn(URI siteUrlEn) {
    this.siteUrlEn = siteUrlEn;
  }


  public Model siteUrlFr(URI siteUrlFr) {
    
    this.siteUrlFr = siteUrlFr;
    return this;
  }

   /**
   * Link to the product on your site. Required when using standalone QR codes (e.g. Print).
   * @return siteUrlFr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link to the product on your site. Required when using standalone QR codes (e.g. Print).")

  public URI getSiteUrlFr() {
    return siteUrlFr;
  }


  public void setSiteUrlFr(URI siteUrlFr) {
    this.siteUrlFr = siteUrlFr;
  }


  public Model siteUrlIt(URI siteUrlIt) {
    
    this.siteUrlIt = siteUrlIt;
    return this;
  }

   /**
   * Link to the product on your site. Required when using standalone QR codes (e.g. Print).
   * @return siteUrlIt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link to the product on your site. Required when using standalone QR codes (e.g. Print).")

  public URI getSiteUrlIt() {
    return siteUrlIt;
  }


  public void setSiteUrlIt(URI siteUrlIt) {
    this.siteUrlIt = siteUrlIt;
  }


  public Model sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * Stock-keeping unit. The identfier of the product in external webstore.
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Stock-keeping unit. The identfier of the product in external webstore.")

  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public Model price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Display price. The effective price is determined by the external webstore.
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display price. The effective price is determined by the external webstore.")

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


   /**
   * Get priceCurrency
   * @return priceCurrency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getPriceCurrency() {
    return priceCurrency;
  }




  public Model scaleable(Boolean scaleable) {
    
    this.scaleable = scaleable;
    return this;
  }

   /**
   * Let&#39;s the user scale the model in AR when enabled.
   * @return scaleable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Let's the user scale the model in AR when enabled.")

  public Boolean getScaleable() {
    return scaleable;
  }


  public void setScaleable(Boolean scaleable) {
    this.scaleable = scaleable;
  }


  public Model glb(URI glb) {
    
    this.glb = glb;
    return this;
  }

   /**
   * Must be a binary glTF file according to the Khronos Group standard.
   * @return glb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Must be a binary glTF file according to the Khronos Group standard.")

  public URI getGlb() {
    return glb;
  }


  public void setGlb(URI glb) {
    this.glb = glb;
  }


  public Model usdz(URI usdz) {
    
    this.usdz = usdz;
    return this;
  }

   /**
   * Must be a USDZ or Reality Composer file.
   * @return usdz
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Must be a USDZ or Reality Composer file.")

  public URI getUsdz() {
    return usdz;
  }


  public void setUsdz(URI usdz) {
    this.usdz = usdz;
  }


  public Model unityIos(URI unityIos) {
    
    this.unityIos = unityIos;
    return this;
  }

   /**
   * Unity Asset Bundle for Android
   * @return unityIos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unity Asset Bundle for Android")

  public URI getUnityIos() {
    return unityIos;
  }


  public void setUnityIos(URI unityIos) {
    this.unityIos = unityIos;
  }


  public Model unityAndroid(URI unityAndroid) {
    
    this.unityAndroid = unityAndroid;
    return this;
  }

   /**
   * Unity Asset Bundle for iOS
   * @return unityAndroid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unity Asset Bundle for iOS")

  public URI getUnityAndroid() {
    return unityAndroid;
  }


  public void setUnityAndroid(URI unityAndroid) {
    this.unityAndroid = unityAndroid;
  }


   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreated() {
    return created;
  }




   /**
   * Get modified
   * @return modified
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getModified() {
    return modified;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model model = (Model) o;
    return Objects.equals(this.id, model.id) &&
        Objects.equals(this.project, model.project) &&
        Objects.equals(this.name, model.name) &&
        Objects.equals(this.nameDe, model.nameDe) &&
        Objects.equals(this.nameEn, model.nameEn) &&
        Objects.equals(this.nameFr, model.nameFr) &&
        Objects.equals(this.nameIt, model.nameIt) &&
        Objects.equals(this.slug, model.slug) &&
        Objects.equals(this.image, model.image) &&
        Objects.equals(this.imageThumb, model.imageThumb) &&
        Objects.equals(this.imagePreview, model.imagePreview) &&
        Objects.equals(this.status, model.status) &&
        Objects.equals(this.description, model.description) &&
        Objects.equals(this.descriptionDe, model.descriptionDe) &&
        Objects.equals(this.descriptionEn, model.descriptionEn) &&
        Objects.equals(this.descriptionFr, model.descriptionFr) &&
        Objects.equals(this.descriptionIt, model.descriptionIt) &&
        Objects.equals(this.number, model.number) &&
        Objects.equals(this.siteUrl, model.siteUrl) &&
        Objects.equals(this.siteUrlDe, model.siteUrlDe) &&
        Objects.equals(this.siteUrlEn, model.siteUrlEn) &&
        Objects.equals(this.siteUrlFr, model.siteUrlFr) &&
        Objects.equals(this.siteUrlIt, model.siteUrlIt) &&
        Objects.equals(this.sku, model.sku) &&
        Objects.equals(this.price, model.price) &&
        Objects.equals(this.priceCurrency, model.priceCurrency) &&
        Objects.equals(this.scaleable, model.scaleable) &&
        Objects.equals(this.glb, model.glb) &&
        Objects.equals(this.usdz, model.usdz) &&
        Objects.equals(this.unityIos, model.unityIos) &&
        Objects.equals(this.unityAndroid, model.unityAndroid) &&
        Objects.equals(this.created, model.created) &&
        Objects.equals(this.modified, model.modified);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, project, name, nameDe, nameEn, nameFr, nameIt, slug, image, imageThumb, imagePreview, status, description, descriptionDe, descriptionEn, descriptionFr, descriptionIt, number, siteUrl, siteUrlDe, siteUrlEn, siteUrlFr, siteUrlIt, sku, price, priceCurrency, scaleable, glb, usdz, unityIos, unityAndroid, created, modified);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameDe: ").append(toIndentedString(nameDe)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    nameFr: ").append(toIndentedString(nameFr)).append("\n");
    sb.append("    nameIt: ").append(toIndentedString(nameIt)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imageThumb: ").append(toIndentedString(imageThumb)).append("\n");
    sb.append("    imagePreview: ").append(toIndentedString(imagePreview)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    descriptionDe: ").append(toIndentedString(descriptionDe)).append("\n");
    sb.append("    descriptionEn: ").append(toIndentedString(descriptionEn)).append("\n");
    sb.append("    descriptionFr: ").append(toIndentedString(descriptionFr)).append("\n");
    sb.append("    descriptionIt: ").append(toIndentedString(descriptionIt)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    siteUrl: ").append(toIndentedString(siteUrl)).append("\n");
    sb.append("    siteUrlDe: ").append(toIndentedString(siteUrlDe)).append("\n");
    sb.append("    siteUrlEn: ").append(toIndentedString(siteUrlEn)).append("\n");
    sb.append("    siteUrlFr: ").append(toIndentedString(siteUrlFr)).append("\n");
    sb.append("    siteUrlIt: ").append(toIndentedString(siteUrlIt)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceCurrency: ").append(toIndentedString(priceCurrency)).append("\n");
    sb.append("    scaleable: ").append(toIndentedString(scaleable)).append("\n");
    sb.append("    glb: ").append(toIndentedString(glb)).append("\n");
    sb.append("    usdz: ").append(toIndentedString(usdz)).append("\n");
    sb.append("    unityIos: ").append(toIndentedString(unityIos)).append("\n");
    sb.append("    unityAndroid: ").append(toIndentedString(unityAndroid)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

