/* tslint:disable */
/* eslint-disable */
/**
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChronicStats
 */
export interface ChronicStats {
    /**
     *
     * @type {string}
     * @memberof ChronicStats
     */
    label: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof ChronicStats
     */
    data: { [key: string]: any };
    /**
     *
     * @type {number}
     * @memberof ChronicStats
     */
    total: number;
}

/**
 * Check if a given object implements the ChronicStats interface.
 */
export function instanceOfChronicStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'label' in value;
    isInstance = isInstance && 'data' in value;
    isInstance = isInstance && 'total' in value;

    return isInstance;
}

export function ChronicStatsFromJSON(json: any): ChronicStats {
    return ChronicStatsFromJSONTyped(json, false);
}

export function ChronicStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChronicStats {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        label: json['label'],
        data: json['data'],
        total: json['total'],
    };
}

export function ChronicStatsToJSON(value?: ChronicStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        label: value.label,
        data: value.data,
        total: value.total,
    };
}
