/* tslint:disable */
/* eslint-disable */
/**
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum GroupByE73Enum {
    All = 'all',
    Events = 'events',
    Models = 'models',
    Platforms = 'platforms',
    Languages = 'languages',
    Devices = 'devices',
    Browsers = 'browsers',
    Countries = 'countries'
}

export function GroupByE73EnumFromJSON(json: any): GroupByE73Enum {
    return GroupByE73EnumFromJSONTyped(json, false);
}

export function GroupByE73EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupByE73Enum {
    return json as GroupByE73Enum;
}

export function GroupByE73EnumToJSON(value?: GroupByE73Enum | null): any {
    return value as any;
}

