/* tslint:disable */
/* eslint-disable */
/**
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PaymentMethodEnum,
    PaymentMethodEnumFromJSON,
    PaymentMethodEnumFromJSONTyped,
    PaymentMethodEnumToJSON,
} from './PaymentMethodEnum';

/**
 * 
 * @export
 * @interface NewSubscription
 */
export interface NewSubscription {
    /**
     * 
     * @type {string}
     * @memberof NewSubscription
     */
    plan: string;
    /**
     * 
     * @type {PaymentMethodEnum}
     * @memberof NewSubscription
     */
    paymentMethod: PaymentMethodEnum;
    /**
     * 
     * @type {boolean}
     * @memberof NewSubscription
     */
    tosAccepted: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewSubscription
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSubscription
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSubscription
     */
    clientSecret?: string;
}

export function NewSubscriptionFromJSON(json: any): NewSubscription {
    return NewSubscriptionFromJSONTyped(json, false);
}

export function NewSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plan': json['plan'],
        'paymentMethod': PaymentMethodEnumFromJSON(json['payment_method']),
        'tosAccepted': json['tos_accepted'],
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'subscriptionId': !exists(json, 'subscription_id') ? undefined : json['subscription_id'],
        'clientSecret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
    };
}

export function NewSubscriptionToJSON(value?: NewSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan': value.plan,
        'payment_method': PaymentMethodEnumToJSON(value.paymentMethod),
        'tos_accepted': value.tosAccepted,
        'customer_id': value.customerId,
        'subscription_id': value.subscriptionId,
        'client_secret': value.clientSecret,
    };
}

