/* tslint:disable */
/* eslint-disable */
/**
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderModelCommentCreate
 */
export interface OrderModelCommentCreate {
    /**
     * 
     * @type {string}
     * @memberof OrderModelCommentCreate
     */
    comment: string;
}

export function OrderModelCommentCreateFromJSON(json: any): OrderModelCommentCreate {
    return OrderModelCommentCreateFromJSONTyped(json, false);
}

export function OrderModelCommentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderModelCommentCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function OrderModelCommentCreateToJSON(value?: OrderModelCommentCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
    };
}

