/* tslint:disable */
/* eslint-disable */
/**
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProjectsStatisticsGroupByEnum {
    All = 'all',
    Events = 'events',
    Models = 'models',
    Platforms = 'platforms',
    Languages = 'languages',
    Devices = 'devices',
    Browsers = 'browsers',
    Countries = 'countries'
}

export function ProjectsStatisticsGroupByEnumFromJSON(json: any): ProjectsStatisticsGroupByEnum {
    return ProjectsStatisticsGroupByEnumFromJSONTyped(json, false);
}

export function ProjectsStatisticsGroupByEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsStatisticsGroupByEnum {
    return json as ProjectsStatisticsGroupByEnum;
}

export function ProjectsStatisticsGroupByEnumToJSON(value?: ProjectsStatisticsGroupByEnum | null): any {
    return value as any;
}

