/* tslint:disable */
/* eslint-disable */
/**
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProrationBehaviorEnum {
    AlwaysInvoice = 'always_invoice',
    CreateProrations = 'create_prorations',
    None = 'none'
}

export function ProrationBehaviorEnumFromJSON(json: any): ProrationBehaviorEnum {
    return ProrationBehaviorEnumFromJSONTyped(json, false);
}

export function ProrationBehaviorEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProrationBehaviorEnum {
    return json as ProrationBehaviorEnum;
}

export function ProrationBehaviorEnumToJSON(value?: ProrationBehaviorEnum | null): any {
    return value as any;
}

