/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Genie.Api.Client;
using Genie.Api.Api;
// uncomment below to import models
//using Genie.Api.Model;

namespace Genie.Api.Test.Api
{
    /// <summary>
    ///  Class for testing PlansApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PlansApiTests : IDisposable
    {
        private PlansApi instance;

        public PlansApiTests()
        {
            instance = new PlansApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlansApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PlansApi
            //Assert.IsType<PlansApi>(instance);
        }

        /// <summary>
        /// Test PlansList
        /// </summary>
        [Fact]
        public void PlansListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PlansList();
            //Assert.IsType<List<PricingPlan>>(response);
        }
    }
}
