/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Genie.Client;
using Genie.Model;

namespace Genie.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICustomerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <returns>Address</returns>
        Address CustomerBillingAddressPartialUpdate(PatchedAddress patchedAddress = default(PatchedAddress));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> CustomerBillingAddressPartialUpdateWithHttpInfo(PatchedAddress patchedAddress = default(PatchedAddress));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Address</returns>
        Address CustomerBillingAddressRetrieve();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> CustomerBillingAddressRetrieveWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <returns>Address</returns>
        Address CustomerBillingAddressUpdate(Address address);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <returns>ApiResponse of Address</returns>
        ApiResponse<Address> CustomerBillingAddressUpdateWithHttpInfo(Address address);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer associated with the current user account
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Customer</returns>
        Customer CustomerRetrieve();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer associated with the current user account
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Customer</returns>
        ApiResponse<Customer> CustomerRetrieveWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICustomerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> CustomerBillingAddressPartialUpdateAsync(PatchedAddress patchedAddress = default(PatchedAddress), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> CustomerBillingAddressPartialUpdateWithHttpInfoAsync(PatchedAddress patchedAddress = default(PatchedAddress), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> CustomerBillingAddressRetrieveAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> CustomerBillingAddressRetrieveWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        System.Threading.Tasks.Task<Address> CustomerBillingAddressUpdateAsync(Address address, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Update customer billing address. Required prior to subscribing to Genie AR services
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        System.Threading.Tasks.Task<ApiResponse<Address>> CustomerBillingAddressUpdateWithHttpInfoAsync(Address address, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer associated with the current user account
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Customer</returns>
        System.Threading.Tasks.Task<Customer> CustomerRetrieveAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns the customer associated with the current user account
        /// </remarks>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Customer)</returns>
        System.Threading.Tasks.Task<ApiResponse<Customer>> CustomerRetrieveWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICustomerApi : ICustomerApiSync, ICustomerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CustomerApi : ICustomerApi
    {
        private Genie.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CustomerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CustomerApi(string basePath)
        {
            this.Configuration = Genie.Client.Configuration.MergeConfigurations(
                Genie.Client.GlobalConfiguration.Instance,
                new Genie.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Genie.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Genie.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Genie.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CustomerApi(Genie.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Genie.Client.Configuration.MergeConfigurations(
                Genie.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Genie.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Genie.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Genie.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CustomerApi(Genie.Client.ISynchronousClient client, Genie.Client.IAsynchronousClient asyncClient, Genie.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Genie.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Genie.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Genie.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Genie.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Genie.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <returns>Address</returns>
        public Address CustomerBillingAddressPartialUpdate(PatchedAddress patchedAddress = default(PatchedAddress))
        {
            Genie.Client.ApiResponse<Address> localVarResponse = CustomerBillingAddressPartialUpdateWithHttpInfo(patchedAddress);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <returns>ApiResponse of Address</returns>
        public Genie.Client.ApiResponse<Address> CustomerBillingAddressPartialUpdateWithHttpInfo(PatchedAddress patchedAddress = default(PatchedAddress))
        {
            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = patchedAddress;

            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressPartialUpdate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> CustomerBillingAddressPartialUpdateAsync(PatchedAddress patchedAddress = default(PatchedAddress), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Genie.Client.ApiResponse<Address> localVarResponse = await CustomerBillingAddressPartialUpdateWithHttpInfoAsync(patchedAddress, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="patchedAddress"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<Genie.Client.ApiResponse<Address>> CustomerBillingAddressPartialUpdateWithHttpInfoAsync(PatchedAddress patchedAddress = default(PatchedAddress), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = patchedAddress;

            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressPartialUpdate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Address</returns>
        public Address CustomerBillingAddressRetrieve()
        {
            Genie.Client.ApiResponse<Address> localVarResponse = CustomerBillingAddressRetrieveWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Address</returns>
        public Genie.Client.ApiResponse<Address> CustomerBillingAddressRetrieveWithHttpInfo()
        {
            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> CustomerBillingAddressRetrieveAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Genie.Client.ApiResponse<Address> localVarResponse = await CustomerBillingAddressRetrieveWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<Genie.Client.ApiResponse<Address>> CustomerBillingAddressRetrieveWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <returns>Address</returns>
        public Address CustomerBillingAddressUpdate(Address address)
        {
            Genie.Client.ApiResponse<Address> localVarResponse = CustomerBillingAddressUpdateWithHttpInfo(address);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <returns>ApiResponse of Address</returns>
        public Genie.Client.ApiResponse<Address> CustomerBillingAddressUpdateWithHttpInfo(Address address)
        {
            // verify the required parameter 'address' is set
            if (address == null)
                throw new Genie.Client.ApiException(400, "Missing required parameter 'address' when calling CustomerApi->CustomerBillingAddressUpdate");

            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = address;

            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressUpdate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Address</returns>
        public async System.Threading.Tasks.Task<Address> CustomerBillingAddressUpdateAsync(Address address, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Genie.Client.ApiResponse<Address> localVarResponse = await CustomerBillingAddressUpdateWithHttpInfoAsync(address, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Update customer billing address. Required prior to subscribing to Genie AR services
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Address)</returns>
        public async System.Threading.Tasks.Task<Genie.Client.ApiResponse<Address>> CustomerBillingAddressUpdateWithHttpInfoAsync(Address address, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'address' is set
            if (address == null)
                throw new Genie.Client.ApiException(400, "Missing required parameter 'address' when calling CustomerApi->CustomerBillingAddressUpdate");


            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = address;

            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Address>("/api/customer/billing_address/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerBillingAddressUpdate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns the customer associated with the current user account
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Customer</returns>
        public Customer CustomerRetrieve()
        {
            Genie.Client.ApiResponse<Customer> localVarResponse = CustomerRetrieveWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns the customer associated with the current user account
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Customer</returns>
        public Genie.Client.ApiResponse<Customer> CustomerRetrieveWithHttpInfo()
        {
            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Customer>("/api/customer/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns the customer associated with the current user account
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Customer</returns>
        public async System.Threading.Tasks.Task<Customer> CustomerRetrieveAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Genie.Client.ApiResponse<Customer> localVarResponse = await CustomerRetrieveWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns the customer associated with the current user account
        /// </summary>
        /// <exception cref="Genie.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Customer)</returns>
        public async System.Threading.Tasks.Task<Genie.Client.ApiResponse<Customer>> CustomerRetrieveWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Genie.Client.RequestOptions localVarRequestOptions = new Genie.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Genie.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Genie.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (cookieAuth) required
            // cookie parameter support
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("sessionid")))
            {
                localVarRequestOptions.Cookies.Add(new Cookie("sessionid", this.Configuration.GetApiKeyWithPrefix("sessionid")));
            }
            // authentication (jwtAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Customer>("/api/customer/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomerRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
