// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'address.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Address _$AddressFromJson(Map<String, dynamic> json) => $checkedCreate(
      'Address',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const ['id', 'name'],
        );
        final val = Address(
          id: $checkedConvert('id', (v) => v as String),
          name: $checkedConvert('name', (v) => v as String),
          email: $checkedConvert('email', (v) => v as String?),
          phone: $checkedConvert('phone', (v) => v as String?),
          line1: $checkedConvert('line1', (v) => v as String?),
          line2: $checkedConvert('line2', (v) => v as String?),
          postalCode: $checkedConvert('postal_code', (v) => v as String?),
          city: $checkedConvert('city', (v) => v as String?),
          state: $checkedConvert('state', (v) => v as String?),
          country: $checkedConvert(
              'country', (v) => $enumDecodeNullable(_$CountryEnumEnumMap, v)),
        );
        return val;
      },
      fieldKeyMap: const {'postalCode': 'postal_code'},
    );

Map<String, dynamic> _$AddressToJson(Address instance) {
  final val = <String, dynamic>{
    'id': instance.id,
    'name': instance.name,
  };

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('email', instance.email);
  writeNotNull('phone', instance.phone);
  writeNotNull('line1', instance.line1);
  writeNotNull('line2', instance.line2);
  writeNotNull('postal_code', instance.postalCode);
  writeNotNull('city', instance.city);
  writeNotNull('state', instance.state);
  writeNotNull('country', _$CountryEnumEnumMap[instance.country]);
  return val;
}

const _$CountryEnumEnumMap = {
  CountryEnum.AF: 'AF',
  CountryEnum.AX: 'AX',
  CountryEnum.AL: 'AL',
  CountryEnum.DZ: 'DZ',
  CountryEnum.AS: 'AS',
  CountryEnum.AD: 'AD',
  CountryEnum.AO: 'AO',
  CountryEnum.AI: 'AI',
  CountryEnum.AQ: 'AQ',
  CountryEnum.AG: 'AG',
  CountryEnum.AR: 'AR',
  CountryEnum.AM: 'AM',
  CountryEnum.AW: 'AW',
  CountryEnum.AU: 'AU',
  CountryEnum.AT: 'AT',
  CountryEnum.AZ: 'AZ',
  CountryEnum.BS: 'BS',
  CountryEnum.BH: 'BH',
  CountryEnum.BD: 'BD',
  CountryEnum.BB: 'BB',
  CountryEnum.BY: 'BY',
  CountryEnum.BE: 'BE',
  CountryEnum.BZ: 'BZ',
  CountryEnum.BJ: 'BJ',
  CountryEnum.BM: 'BM',
  CountryEnum.BT: 'BT',
  CountryEnum.BO: 'BO',
  CountryEnum.BQ: 'BQ',
  CountryEnum.BA: 'BA',
  CountryEnum.BW: 'BW',
  CountryEnum.BV: 'BV',
  CountryEnum.BR: 'BR',
  CountryEnum.IO: 'IO',
  CountryEnum.BN: 'BN',
  CountryEnum.BG: 'BG',
  CountryEnum.BF: 'BF',
  CountryEnum.BI: 'BI',
  CountryEnum.CV: 'CV',
  CountryEnum.KH: 'KH',
  CountryEnum.CM: 'CM',
  CountryEnum.CA: 'CA',
  CountryEnum.KY: 'KY',
  CountryEnum.CF: 'CF',
  CountryEnum.TD: 'TD',
  CountryEnum.CL: 'CL',
  CountryEnum.CN: 'CN',
  CountryEnum.CX: 'CX',
  CountryEnum.CC: 'CC',
  CountryEnum.CO: 'CO',
  CountryEnum.KM: 'KM',
  CountryEnum.CG: 'CG',
  CountryEnum.CD: 'CD',
  CountryEnum.CK: 'CK',
  CountryEnum.CR: 'CR',
  CountryEnum.CI: 'CI',
  CountryEnum.HR: 'HR',
  CountryEnum.CU: 'CU',
  CountryEnum.CW: 'CW',
  CountryEnum.CY: 'CY',
  CountryEnum.CZ: 'CZ',
  CountryEnum.DK: 'DK',
  CountryEnum.DJ: 'DJ',
  CountryEnum.DM: 'DM',
  CountryEnum.DO: 'DO',
  CountryEnum.EC: 'EC',
  CountryEnum.EG: 'EG',
  CountryEnum.SV: 'SV',
  CountryEnum.GQ: 'GQ',
  CountryEnum.ER: 'ER',
  CountryEnum.EE: 'EE',
  CountryEnum.SZ: 'SZ',
  CountryEnum.ET: 'ET',
  CountryEnum.FK: 'FK',
  CountryEnum.FO: 'FO',
  CountryEnum.FJ: 'FJ',
  CountryEnum.FI: 'FI',
  CountryEnum.FR: 'FR',
  CountryEnum.GF: 'GF',
  CountryEnum.PF: 'PF',
  CountryEnum.TF: 'TF',
  CountryEnum.GA: 'GA',
  CountryEnum.GM: 'GM',
  CountryEnum.GE: 'GE',
  CountryEnum.DE: 'DE',
  CountryEnum.GH: 'GH',
  CountryEnum.GI: 'GI',
  CountryEnum.GR: 'GR',
  CountryEnum.GL: 'GL',
  CountryEnum.GD: 'GD',
  CountryEnum.GP: 'GP',
  CountryEnum.GU: 'GU',
  CountryEnum.GT: 'GT',
  CountryEnum.GG: 'GG',
  CountryEnum.GN: 'GN',
  CountryEnum.GW: 'GW',
  CountryEnum.GY: 'GY',
  CountryEnum.HT: 'HT',
  CountryEnum.HM: 'HM',
  CountryEnum.VA: 'VA',
  CountryEnum.HN: 'HN',
  CountryEnum.HK: 'HK',
  CountryEnum.HU: 'HU',
  CountryEnum.IS: 'IS',
  CountryEnum.IN: 'IN',
  CountryEnum.ID: 'ID',
  CountryEnum.IR: 'IR',
  CountryEnum.IQ: 'IQ',
  CountryEnum.IE: 'IE',
  CountryEnum.IM: 'IM',
  CountryEnum.IL: 'IL',
  CountryEnum.IT: 'IT',
  CountryEnum.JM: 'JM',
  CountryEnum.JP: 'JP',
  CountryEnum.JE: 'JE',
  CountryEnum.JO: 'JO',
  CountryEnum.KZ: 'KZ',
  CountryEnum.KE: 'KE',
  CountryEnum.KI: 'KI',
  CountryEnum.KW: 'KW',
  CountryEnum.KG: 'KG',
  CountryEnum.LA: 'LA',
  CountryEnum.LV: 'LV',
  CountryEnum.LB: 'LB',
  CountryEnum.LS: 'LS',
  CountryEnum.LR: 'LR',
  CountryEnum.LY: 'LY',
  CountryEnum.LI: 'LI',
  CountryEnum.LT: 'LT',
  CountryEnum.LU: 'LU',
  CountryEnum.MO: 'MO',
  CountryEnum.MG: 'MG',
  CountryEnum.MW: 'MW',
  CountryEnum.MY: 'MY',
  CountryEnum.MV: 'MV',
  CountryEnum.ML: 'ML',
  CountryEnum.MT: 'MT',
  CountryEnum.MH: 'MH',
  CountryEnum.MQ: 'MQ',
  CountryEnum.MR: 'MR',
  CountryEnum.MU: 'MU',
  CountryEnum.YT: 'YT',
  CountryEnum.MX: 'MX',
  CountryEnum.FM: 'FM',
  CountryEnum.MD: 'MD',
  CountryEnum.MC: 'MC',
  CountryEnum.MN: 'MN',
  CountryEnum.ME: 'ME',
  CountryEnum.MS: 'MS',
  CountryEnum.MA: 'MA',
  CountryEnum.MZ: 'MZ',
  CountryEnum.MM: 'MM',
  CountryEnum.NA: 'NA',
  CountryEnum.NR: 'NR',
  CountryEnum.NP: 'NP',
  CountryEnum.NL: 'NL',
  CountryEnum.NC: 'NC',
  CountryEnum.NZ: 'NZ',
  CountryEnum.NI: 'NI',
  CountryEnum.NE: 'NE',
  CountryEnum.NG: 'NG',
  CountryEnum.NU: 'NU',
  CountryEnum.NF: 'NF',
  CountryEnum.KP: 'KP',
  CountryEnum.MK: 'MK',
  CountryEnum.MP: 'MP',
  CountryEnum.NO: 'NO',
  CountryEnum.OM: 'OM',
  CountryEnum.PK: 'PK',
  CountryEnum.PW: 'PW',
  CountryEnum.PS: 'PS',
  CountryEnum.PA: 'PA',
  CountryEnum.PG: 'PG',
  CountryEnum.PY: 'PY',
  CountryEnum.PE: 'PE',
  CountryEnum.PH: 'PH',
  CountryEnum.PN: 'PN',
  CountryEnum.PL: 'PL',
  CountryEnum.PT: 'PT',
  CountryEnum.PR: 'PR',
  CountryEnum.QA: 'QA',
  CountryEnum.RE: 'RE',
  CountryEnum.RO: 'RO',
  CountryEnum.RU: 'RU',
  CountryEnum.RW: 'RW',
  CountryEnum.BL: 'BL',
  CountryEnum.SH: 'SH',
  CountryEnum.KN: 'KN',
  CountryEnum.LC: 'LC',
  CountryEnum.MF: 'MF',
  CountryEnum.PM: 'PM',
  CountryEnum.VC: 'VC',
  CountryEnum.WS: 'WS',
  CountryEnum.SM: 'SM',
  CountryEnum.ST: 'ST',
  CountryEnum.SA: 'SA',
  CountryEnum.SN: 'SN',
  CountryEnum.RS: 'RS',
  CountryEnum.SC: 'SC',
  CountryEnum.SL: 'SL',
  CountryEnum.SG: 'SG',
  CountryEnum.SX: 'SX',
  CountryEnum.SK: 'SK',
  CountryEnum.SI: 'SI',
  CountryEnum.SB: 'SB',
  CountryEnum.SO: 'SO',
  CountryEnum.ZA: 'ZA',
  CountryEnum.GS: 'GS',
  CountryEnum.KR: 'KR',
  CountryEnum.SS: 'SS',
  CountryEnum.ES: 'ES',
  CountryEnum.LK: 'LK',
  CountryEnum.SD: 'SD',
  CountryEnum.SR: 'SR',
  CountryEnum.SJ: 'SJ',
  CountryEnum.SE: 'SE',
  CountryEnum.CH: 'CH',
  CountryEnum.SY: 'SY',
  CountryEnum.TW: 'TW',
  CountryEnum.TJ: 'TJ',
  CountryEnum.TZ: 'TZ',
  CountryEnum.TH: 'TH',
  CountryEnum.TL: 'TL',
  CountryEnum.TG: 'TG',
  CountryEnum.TK: 'TK',
  CountryEnum.TO: 'TO',
  CountryEnum.TT: 'TT',
  CountryEnum.TN: 'TN',
  CountryEnum.TR: 'TR',
  CountryEnum.TM: 'TM',
  CountryEnum.TC: 'TC',
  CountryEnum.TV: 'TV',
  CountryEnum.UG: 'UG',
  CountryEnum.UA: 'UA',
  CountryEnum.AE: 'AE',
  CountryEnum.GB: 'GB',
  CountryEnum.UM: 'UM',
  CountryEnum.US: 'US',
  CountryEnum.UY: 'UY',
  CountryEnum.UZ: 'UZ',
  CountryEnum.VU: 'VU',
  CountryEnum.VE: 'VE',
  CountryEnum.VN: 'VN',
  CountryEnum.VG: 'VG',
  CountryEnum.VI: 'VI',
  CountryEnum.WF: 'WF',
  CountryEnum.EH: 'EH',
  CountryEnum.YE: 'YE',
  CountryEnum.ZM: 'ZM',
  CountryEnum.ZW: 'ZW',
};
