/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api.Api;
using Genie.Api.Model;
using Genie.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Nested
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NestedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Nested
        //private Nested instance;

        public NestedTests()
        {
            // TODO uncomment below to create an instance of Nested
            //instance = new Nested();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Nested
        /// </summary>
        [Fact]
        public void NestedInstanceTest()
        {
            // TODO uncomment below to test "IsType" Nested
            //Assert.IsType<Nested>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'ProjectQuotas'
        /// </summary>
        [Fact]
        public void ProjectQuotasTest()
        {
            // TODO unit test for the property 'ProjectQuotas'
        }
        /// <summary>
        /// Test the property 'ModelQuotas'
        /// </summary>
        [Fact]
        public void ModelQuotasTest()
        {
            // TODO unit test for the property 'ModelQuotas'
        }
        /// <summary>
        /// Test the property 'ViewQuotas'
        /// </summary>
        [Fact]
        public void ViewQuotasTest()
        {
            // TODO unit test for the property 'ViewQuotas'
        }
        /// <summary>
        /// Test the property 'SeoOptimization'
        /// </summary>
        [Fact]
        public void SeoOptimizationTest()
        {
            // TODO unit test for the property 'SeoOptimization'
        }
        /// <summary>
        /// Test the property 'ViewReporting'
        /// </summary>
        [Fact]
        public void ViewReportingTest()
        {
            // TODO unit test for the property 'ViewReporting'
        }
        /// <summary>
        /// Test the property 'CustomQrCodes'
        /// </summary>
        [Fact]
        public void CustomQrCodesTest()
        {
            // TODO unit test for the property 'CustomQrCodes'
        }
        /// <summary>
        /// Test the property 'StripePriceId'
        /// </summary>
        [Fact]
        public void StripePriceIdTest()
        {
            // TODO unit test for the property 'StripePriceId'
        }

    }

}
