/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api.Api;
using Genie.Api.Model;
using Genie.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Api.Test.Model
{
    /// <summary>
    ///  Class for testing NewSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewSubscription
        //private NewSubscription instance;

        public NewSubscriptionTests()
        {
            // TODO uncomment below to create an instance of NewSubscription
            //instance = new NewSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewSubscription
        /// </summary>
        [Fact]
        public void NewSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewSubscription
            //Assert.IsType<NewSubscription>(instance);
        }


        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'TosAccepted'
        /// </summary>
        [Fact]
        public void TosAcceptedTest()
        {
            // TODO unit test for the property 'TosAccepted'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }

    }

}
