/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api.Api;
using Genie.Api.Model;
using Genie.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PasswordReset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PasswordResetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PasswordReset
        //private PasswordReset instance;

        public PasswordResetTests()
        {
            // TODO uncomment below to create an instance of PasswordReset
            //instance = new PasswordReset();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PasswordReset
        /// </summary>
        [Fact]
        public void PasswordResetInstanceTest()
        {
            // TODO uncomment below to test "IsType" PasswordReset
            //Assert.IsType<PasswordReset>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
