/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api.Api;
using Genie.Api.Model;
using Genie.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        public ProjectTests()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Fact]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" Project
            //Assert.IsType<Project>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'ImageThumb'
        /// </summary>
        [Fact]
        public void ImageThumbTest()
        {
            // TODO unit test for the property 'ImageThumb'
        }
        /// <summary>
        /// Test the property 'ImagePreview'
        /// </summary>
        [Fact]
        public void ImagePreviewTest()
        {
            // TODO unit test for the property 'ImagePreview'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Gallery'
        /// </summary>
        [Fact]
        public void GalleryTest()
        {
            // TODO unit test for the property 'Gallery'
        }
        /// <summary>
        /// Test the property 'TranslationsDe'
        /// </summary>
        [Fact]
        public void TranslationsDeTest()
        {
            // TODO unit test for the property 'TranslationsDe'
        }
        /// <summary>
        /// Test the property 'TranslationsEn'
        /// </summary>
        [Fact]
        public void TranslationsEnTest()
        {
            // TODO unit test for the property 'TranslationsEn'
        }
        /// <summary>
        /// Test the property 'TranslationsFr'
        /// </summary>
        [Fact]
        public void TranslationsFrTest()
        {
            // TODO unit test for the property 'TranslationsFr'
        }
        /// <summary>
        /// Test the property 'TranslationsIt'
        /// </summary>
        [Fact]
        public void TranslationsItTest()
        {
            // TODO unit test for the property 'TranslationsIt'
        }
        /// <summary>
        /// Test the property 'BacklinkUrls'
        /// </summary>
        [Fact]
        public void BacklinkUrlsTest()
        {
            // TODO unit test for the property 'BacklinkUrls'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

    }

}
