/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Genie.Api.Api;
using Genie.Api.Model;
using Genie.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Genie.Api.Test.Model
{
    /// <summary>
    ///  Class for testing StripeSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StripeSubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StripeSubscription
        //private StripeSubscription instance;

        public StripeSubscriptionTests()
        {
            // TODO uncomment below to create an instance of StripeSubscription
            //instance = new StripeSubscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StripeSubscription
        /// </summary>
        [Fact]
        public void StripeSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" StripeSubscription
            //Assert.IsType<StripeSubscription>(instance);
        }


        /// <summary>
        /// Test the property 'DjstripeId'
        /// </summary>
        [Fact]
        public void DjstripeIdTest()
        {
            // TODO unit test for the property 'DjstripeId'
        }
        /// <summary>
        /// Test the property 'DjstripeCreated'
        /// </summary>
        [Fact]
        public void DjstripeCreatedTest()
        {
            // TODO unit test for the property 'DjstripeCreated'
        }
        /// <summary>
        /// Test the property 'DjstripeUpdated'
        /// </summary>
        [Fact]
        public void DjstripeUpdatedTest()
        {
            // TODO unit test for the property 'DjstripeUpdated'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ApplicationFeePercent'
        /// </summary>
        [Fact]
        public void ApplicationFeePercentTest()
        {
            // TODO unit test for the property 'ApplicationFeePercent'
        }
        /// <summary>
        /// Test the property 'BillingCycleAnchor'
        /// </summary>
        [Fact]
        public void BillingCycleAnchorTest()
        {
            // TODO unit test for the property 'BillingCycleAnchor'
        }
        /// <summary>
        /// Test the property 'BillingThresholds'
        /// </summary>
        [Fact]
        public void BillingThresholdsTest()
        {
            // TODO unit test for the property 'BillingThresholds'
        }
        /// <summary>
        /// Test the property 'CancelAt'
        /// </summary>
        [Fact]
        public void CancelAtTest()
        {
            // TODO unit test for the property 'CancelAt'
        }
        /// <summary>
        /// Test the property 'CancelAtPeriodEnd'
        /// </summary>
        [Fact]
        public void CancelAtPeriodEndTest()
        {
            // TODO unit test for the property 'CancelAtPeriodEnd'
        }
        /// <summary>
        /// Test the property 'CanceledAt'
        /// </summary>
        [Fact]
        public void CanceledAtTest()
        {
            // TODO unit test for the property 'CanceledAt'
        }
        /// <summary>
        /// Test the property 'CollectionMethod'
        /// </summary>
        [Fact]
        public void CollectionMethodTest()
        {
            // TODO unit test for the property 'CollectionMethod'
        }
        /// <summary>
        /// Test the property 'CurrentPeriodEnd'
        /// </summary>
        [Fact]
        public void CurrentPeriodEndTest()
        {
            // TODO unit test for the property 'CurrentPeriodEnd'
        }
        /// <summary>
        /// Test the property 'CurrentPeriodStart'
        /// </summary>
        [Fact]
        public void CurrentPeriodStartTest()
        {
            // TODO unit test for the property 'CurrentPeriodStart'
        }
        /// <summary>
        /// Test the property 'DaysUntilDue'
        /// </summary>
        [Fact]
        public void DaysUntilDueTest()
        {
            // TODO unit test for the property 'DaysUntilDue'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'EndedAt'
        /// </summary>
        [Fact]
        public void EndedAtTest()
        {
            // TODO unit test for the property 'EndedAt'
        }
        /// <summary>
        /// Test the property 'NextPendingInvoiceItemInvoice'
        /// </summary>
        [Fact]
        public void NextPendingInvoiceItemInvoiceTest()
        {
            // TODO unit test for the property 'NextPendingInvoiceItemInvoice'
        }
        /// <summary>
        /// Test the property 'PendingInvoiceItemInterval'
        /// </summary>
        [Fact]
        public void PendingInvoiceItemIntervalTest()
        {
            // TODO unit test for the property 'PendingInvoiceItemInterval'
        }
        /// <summary>
        /// Test the property 'PendingUpdate'
        /// </summary>
        [Fact]
        public void PendingUpdateTest()
        {
            // TODO unit test for the property 'PendingUpdate'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TrialEnd'
        /// </summary>
        [Fact]
        public void TrialEndTest()
        {
            // TODO unit test for the property 'TrialEnd'
        }
        /// <summary>
        /// Test the property 'TrialStart'
        /// </summary>
        [Fact]
        public void TrialStartTest()
        {
            // TODO unit test for the property 'TrialStart'
        }
        /// <summary>
        /// Test the property 'DjstripeOwnerAccount'
        /// </summary>
        [Fact]
        public void DjstripeOwnerAccountTest()
        {
            // TODO unit test for the property 'DjstripeOwnerAccount'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'DefaultPaymentMethod'
        /// </summary>
        [Fact]
        public void DefaultPaymentMethodTest()
        {
            // TODO unit test for the property 'DefaultPaymentMethod'
        }
        /// <summary>
        /// Test the property 'DefaultSource'
        /// </summary>
        [Fact]
        public void DefaultSourceTest()
        {
            // TODO unit test for the property 'DefaultSource'
        }
        /// <summary>
        /// Test the property 'PendingSetupIntent'
        /// </summary>
        [Fact]
        public void PendingSetupIntentTest()
        {
            // TODO unit test for the property 'PendingSetupIntent'
        }
        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'DefaultTaxRates'
        /// </summary>
        [Fact]
        public void DefaultTaxRatesTest()
        {
            // TODO unit test for the property 'DefaultTaxRates'
        }

    }

}
