/*
 * Genie API
 *
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Genie.Api.Client.OpenAPIDateConverter;

namespace Genie.Api.Model
{
    /// <summary>
    /// TokenRefreshRequest
    /// </summary>
    [DataContract(Name = "TokenRefreshRequest")]
    public partial class TokenRefreshRequest : IEquatable<TokenRefreshRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRefreshRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TokenRefreshRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRefreshRequest" /> class.
        /// </summary>
        /// <param name="refresh">refresh (required).</param>
        public TokenRefreshRequest(string refresh = default(string))
        {
            // to ensure "refresh" is required (not null)
            if (refresh == null) {
                throw new ArgumentNullException("refresh is a required property for TokenRefreshRequest and cannot be null");
            }
            this.Refresh = refresh;
        }

        /// <summary>
        /// Gets or Sets Refresh
        /// </summary>
        [DataMember(Name = "refresh", IsRequired = true, EmitDefaultValue = false)]
        public string Refresh { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokenRefreshRequest {\n");
            sb.Append("  Refresh: ").Append(Refresh).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokenRefreshRequest);
        }

        /// <summary>
        /// Returns true if TokenRefreshRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TokenRefreshRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenRefreshRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Refresh == input.Refresh ||
                    (this.Refresh != null &&
                    this.Refresh.Equals(input.Refresh))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Refresh != null)
                    hashCode = hashCode * 59 + this.Refresh.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
