//
// HealthStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthStatus: Codable, JSONEncodable, Hashable {

    public var dbUp: Bool
    public var storageUp: Bool
    public var cacheUp: Bool

    public init(dbUp: Bool, storageUp: Bool, cacheUp: Bool) {
        self.dbUp = dbUp
        self.storageUp = storageUp
        self.cacheUp = cacheUp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dbUp = "db_up"
        case storageUp = "storage_up"
        case cacheUp = "cache_up"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dbUp, forKey: .dbUp)
        try container.encode(storageUp, forKey: .storageUp)
        try container.encode(cacheUp, forKey: .cacheUp)
    }
}

