/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HealthStatus
 */
public class HealthStatusTest {
    private final HealthStatus model = new HealthStatus();

    /**
     * Model tests for HealthStatus
     */
    @Test
    public void testHealthStatus() {
        // TODO: test HealthStatus
    }

    /**
     * Test the property 'dbUp'
     */
    @Test
    public void dbUpTest() {
        // TODO: test dbUp
    }

    /**
     * Test the property 'storageUp'
     */
    @Test
    public void storageUpTest() {
        // TODO: test storageUp
    }

    /**
     * Test the property 'cacheUp'
     */
    @Test
    public void cacheUpTest() {
        // TODO: test cacheUp
    }

}
