/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import yago.client.models.ModelStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Model
 */
public class ModelTest {
    private final Model model = new Model();

    /**
     * Model tests for Model
     */
    @Test
    public void testModel() {
        // TODO: test Model
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameDe'
     */
    @Test
    public void nameDeTest() {
        // TODO: test nameDe
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

    /**
     * Test the property 'nameFr'
     */
    @Test
    public void nameFrTest() {
        // TODO: test nameFr
    }

    /**
     * Test the property 'nameIt'
     */
    @Test
    public void nameItTest() {
        // TODO: test nameIt
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'imageThumb'
     */
    @Test
    public void imageThumbTest() {
        // TODO: test imageThumb
    }

    /**
     * Test the property 'imagePreview'
     */
    @Test
    public void imagePreviewTest() {
        // TODO: test imagePreview
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'descriptionDe'
     */
    @Test
    public void descriptionDeTest() {
        // TODO: test descriptionDe
    }

    /**
     * Test the property 'descriptionEn'
     */
    @Test
    public void descriptionEnTest() {
        // TODO: test descriptionEn
    }

    /**
     * Test the property 'descriptionFr'
     */
    @Test
    public void descriptionFrTest() {
        // TODO: test descriptionFr
    }

    /**
     * Test the property 'descriptionIt'
     */
    @Test
    public void descriptionItTest() {
        // TODO: test descriptionIt
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'siteUrl'
     */
    @Test
    public void siteUrlTest() {
        // TODO: test siteUrl
    }

    /**
     * Test the property 'siteUrlDe'
     */
    @Test
    public void siteUrlDeTest() {
        // TODO: test siteUrlDe
    }

    /**
     * Test the property 'siteUrlEn'
     */
    @Test
    public void siteUrlEnTest() {
        // TODO: test siteUrlEn
    }

    /**
     * Test the property 'siteUrlFr'
     */
    @Test
    public void siteUrlFrTest() {
        // TODO: test siteUrlFr
    }

    /**
     * Test the property 'siteUrlIt'
     */
    @Test
    public void siteUrlItTest() {
        // TODO: test siteUrlIt
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'priceCurrency'
     */
    @Test
    public void priceCurrencyTest() {
        // TODO: test priceCurrency
    }

    /**
     * Test the property 'scaleable'
     */
    @Test
    public void scaleableTest() {
        // TODO: test scaleable
    }

    /**
     * Test the property 'glb'
     */
    @Test
    public void glbTest() {
        // TODO: test glb
    }

    /**
     * Test the property 'usdz'
     */
    @Test
    public void usdzTest() {
        // TODO: test usdz
    }

    /**
     * Test the property 'unityIos'
     */
    @Test
    public void unityIosTest() {
        // TODO: test unityIos
    }

    /**
     * Test the property 'unityAndroid'
     */
    @Test
    public void unityAndroidTest() {
        // TODO: test unityAndroid
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

}
