/*
 * Genie API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelCreate
 */
public class ModelCreateTest {
    private final ModelCreate model = new ModelCreate();

    /**
     * Model tests for ModelCreate
     */
    @Test
    public void testModelCreate() {
        // TODO: test ModelCreate
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'nameDe'
     */
    @Test
    public void nameDeTest() {
        // TODO: test nameDe
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

    /**
     * Test the property 'nameFr'
     */
    @Test
    public void nameFrTest() {
        // TODO: test nameFr
    }

    /**
     * Test the property 'nameIt'
     */
    @Test
    public void nameItTest() {
        // TODO: test nameIt
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

}
