/*
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderModelCreate
 */
public class OrderModelCreateTest {
    private final OrderModelCreate model = new OrderModelCreate();

    /**
     * Model tests for OrderModelCreate
     */
    @Test
    public void testOrderModelCreate() {
        // TODO: test OrderModelCreate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'widthMm'
     */
    @Test
    public void widthMmTest() {
        // TODO: test widthMm
    }

    /**
     * Test the property 'heightMm'
     */
    @Test
    public void heightMmTest() {
        // TODO: test heightMm
    }

    /**
     * Test the property 'depthMm'
     */
    @Test
    public void depthMmTest() {
        // TODO: test depthMm
    }

}
