/*
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PasswordResetConfirm
 */
public class PasswordResetConfirmTest {
    private final PasswordResetConfirm model = new PasswordResetConfirm();

    /**
     * Model tests for PasswordResetConfirm
     */
    @Test
    public void testPasswordResetConfirm() {
        // TODO: test PasswordResetConfirm
    }

    /**
     * Test the property 'newPassword1'
     */
    @Test
    public void newPassword1Test() {
        // TODO: test newPassword1
    }

    /**
     * Test the property 'newPassword2'
     */
    @Test
    public void newPassword2Test() {
        // TODO: test newPassword2
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
