/*
 * Yago API
 * Augemented Reality Made Easy.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@genie-ar.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yago.client.models;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentMethodEnum
 */
public class PaymentMethodEnumTest {
    /**
     * Model tests for PaymentMethodEnum
     */
    @Test
    public void testPaymentMethodEnum() {
        // TODO: test PaymentMethodEnum
    }

}
